"""initial schema

Revision ID: 2208d981358e
Revises: 
Create Date: 2026-03-17 18:16:54.446970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2208d981358e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aoregistrationsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_bceid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applicant_sr_num', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applicant_sin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step_reached', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('disclaimeracknowledgement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eligibilityratetable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rate_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibilityratetable_rate_key'), 'eligibilityratetable', ['rate_key'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bceid_guid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bceid_guid'), 'user', ['bceid_guid'], unique=True)
    op.create_table('workerauditrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('worker_idir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workerauditrecord_client_portal_id'), 'workerauditrecord', ['client_portal_id'], unique=False)
    op.create_index(op.f('ix_workerauditrecord_worker_idir'), 'workerauditrecord', ['worker_idir'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('portal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mis_person_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_portal_id'), 'profile', ['portal_id'], unique=True)
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=False)
    op.create_table('registrationsession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('invite_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('form_state_json', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_registrationsession_user_id'), 'registrationsession', ['user_id'], unique=False)
    op.create_table('pinresettoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_pinresettoken_profile_id'), 'pinresettoken', ['profile_id'], unique=False)
    op.create_table('plansignaturesession',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('ep_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_plansignaturesession_profile_id'), 'plansignaturesession', ['profile_id'], unique=False)
    op.create_table('srdraft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('sr_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('form_state_json', sa.JSON(), nullable=True),
    sa.Column('portal_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icm_sr_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_srdraft_profile_id'), 'srdraft', ['profile_id'], unique=False)
    op.create_table('attachmentrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('sr_draft_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('av_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['sr_draft_id'], ['srdraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachmentrecord_profile_id'), 'attachmentrecord', ['profile_id'], unique=False)
    op.create_table('scanjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachmentrecord.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attachment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scanjob')
    op.drop_index(op.f('ix_attachmentrecord_profile_id'), table_name='attachmentrecord')
    op.drop_table('attachmentrecord')
    op.drop_index(op.f('ix_srdraft_profile_id'), table_name='srdraft')
    op.drop_table('srdraft')
    op.drop_index(op.f('ix_plansignaturesession_profile_id'), table_name='plansignaturesession')
    op.drop_table('plansignaturesession')
    op.drop_index(op.f('ix_pinresettoken_profile_id'), table_name='pinresettoken')
    op.drop_table('pinresettoken')
    op.drop_index(op.f('ix_registrationsession_user_id'), table_name='registrationsession')
    op.drop_table('registrationsession')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_index(op.f('ix_profile_portal_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_workerauditrecord_worker_idir'), table_name='workerauditrecord')
    op.drop_index(op.f('ix_workerauditrecord_client_portal_id'), table_name='workerauditrecord')
    op.drop_table('workerauditrecord')
    op.drop_index(op.f('ix_user_bceid_guid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_eligibilityratetable_rate_key'), table_name='eligibilityratetable')
    op.drop_table('eligibilityratetable')
    op.drop_table('disclaimeracknowledgement')
    op.drop_table('aoregistrationsession')
    # ### end Alembic commands ###
